package com.sinistralis.AdventureFramework.Stats.Attributes;

//TODO: These are examples, this should be populated via a config... this will likely need a class to manage it
public enum AttributeName
{
    HEALTH,
    SHIELD,
    ENERGY,
    MANA,

    DAMAGE,
    POWER,
    ACCURACY,
    ATTACKSPEED,
    RECOVERYTIME,
    ARMORPIERCING,

    ELEMENTALFOCI_ALL,
    ELEMENTALFOCI_FIRE,
    ELEMENTALFOCI_EARTH,
    ELEMENTALFOCI_WIND,
    ELEMENTALFOCI_ICE,
    ELEMENTALFOCI_VOID,
    ELEMENTALFOCI_DIVINE,
    ELEMENTALFOCI_ARCANE,
    CONCENTRATION,

    CRITICAL_PHYSICAL,
    CRITICAL_MAGICAL,
    HASTE,
    AFFINITY,

    ARMOR,
    ABSORPTION,
    DEFLECTION,
    RESISTANCE_ALL,
    RESISTANCE_FIRE,
    RESISTANCE_EARTH,
    RESISTANCE_WIND,
    RESISTANCE_ICE,
    RESISTANCE_VOID,
    RESISTANCE_DIVINE,
    RESISTANCE_ARCANE,

    MOVESPEED,
    SPRINTMODIFIER,
    JUMP_HEIGHT,
    BLOCK,
}
